---
title: "Analysis_1"
author: "Kenny Smith • smithken@stanford.edu"
date: "2016.5.13"
output: html_document
---

```{r}
require(stats)
```

```{r}
rowVars <- function(x) {
  rowSums((x - rowMeans(x))^2)/(dim(x)[2] - 1)
}
```

```{r}
df <- read.csv("/Users/Jason/Desktop/SETI_TimeSeries/DATA/temp.csv")

names <- df[,1]
loss <- df[,2]
X <- as.matrix(df[,c(-1, -2)])

means <- rowMeans(X)
sds <- sqrt(rowVars(X))
rms_change <- sqrt(rowSums((X[,2:129] - X[,1:128])^2))

plot(sds, means)
plot(sds, rms_change)
plot(means, rms_change)

n <- 128
f <- log(abs(fft(X[1,], n)))[2:(n/2 + 1)]
plot(f)

par(mfrow=c(1, 3))

for (i in 1:5) {
  acf(X[i,], main=paste("ACF", i))
  pacf(X[i,], main=paste("PACF", i))
  plot(X[i,], type="l", main="Time Series", ylim=c(0, 833))
}

D_X <- X[,2:129] - X[,1:128]

for (i in 1:5) {
  acf(D_X[i,], main=paste("Diff ACF", i))
  pacf(D_X[i,], main=paste("Diff PACF", i))
  plot(X[i,], type="l", main="Time Series", ylim=c(0, 833))
}
```

ARIMA MODEL

```{r}
X <- as.matrix(df[,c(-1, -2)])

TS_params <- matrix(NA, dim(X)[1], 2)

for (i in 1:dim(X)[1]) {
  if (i %in% c(29,101,148,231,457,516,540,691,746,799,801)) {
    next
  }
  TS_params[i,] <- arima(X[i,], order=c(1,1, 1))$coef
}

write.csv(TS_params)
```
